<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 4 ANOVAs Part I – HHS627 Textbook2</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter 3 Data Management and R.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter 4 ANOVAs Part I.html"><span class="chapter-title">Chapter 4 ANOVAs Part I</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">HHS627 Textbook2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">HHS 627 Textbook</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 1 HHS Statistical Thinking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 1 HHS Statistical Thinking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 2 Matching Research Designs to Analyses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 2 Matching Research Designs to Analyses</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 3 Data Management and R.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 3: Data Cleaning and Getting into R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 4 ANOVAs Part I.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Chapter 4 ANOVAs Part I</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#anova-part-i" id="toc-anova-part-i" class="nav-link active" data-scroll-target="#anova-part-i">ANOVA: Part I</a></li>
  <li><a href="#what-is-an-anova-why-would-you-do-one" id="toc-what-is-an-anova-why-would-you-do-one" class="nav-link" data-scroll-target="#what-is-an-anova-why-would-you-do-one">What is an ANOVA? Why would you do one?</a></li>
  <li><a href="#technical-details-about-anovas" id="toc-technical-details-about-anovas" class="nav-link" data-scroll-target="#technical-details-about-anovas">Technical Details about ANOVAs</a>
  <ul class="collapse">
  <li><a href="#why-cant-we-just-stick-with-t-tests" id="toc-why-cant-we-just-stick-with-t-tests" class="nav-link" data-scroll-target="#why-cant-we-just-stick-with-t-tests">Why can’t we just stick with <span class="math inline">\(t-tests\)</span>?</a></li>
  <li><a href="#anova-overcomes-the-alpha-inflation-problem-by-focusing-on-one-test." id="toc-anova-overcomes-the-alpha-inflation-problem-by-focusing-on-one-test." class="nav-link" data-scroll-target="#anova-overcomes-the-alpha-inflation-problem-by-focusing-on-one-test.">ANOVA overcomes the alpha inflation problem by focusing on one test.</a></li>
  </ul></li>
  <li><a href="#one-way-anova-details" id="toc-one-way-anova-details" class="nav-link" data-scroll-target="#one-way-anova-details">One Way ANOVA details</a></li>
  <li><a href="#the-logic-of-anova" id="toc-the-logic-of-anova" class="nav-link" data-scroll-target="#the-logic-of-anova">The Logic of ANOVA</a></li>
  <li><a href="#understanding-the-f-ratio" id="toc-understanding-the-f-ratio" class="nav-link" data-scroll-target="#understanding-the-f-ratio">Understanding the F Ratio</a>
  <ul class="collapse">
  <li><a href="#computing-the-f-ratio" id="toc-computing-the-f-ratio" class="nav-link" data-scroll-target="#computing-the-f-ratio">Computing the F Ratio</a></li>
  <li><a href="#example-culture-based-conflicts-with-parents-by-level-of-language-brokering" id="toc-example-culture-based-conflicts-with-parents-by-level-of-language-brokering" class="nav-link" data-scroll-target="#example-culture-based-conflicts-with-parents-by-level-of-language-brokering">Example: Culture-based conflicts with parents by level of language brokering</a></li>
  </ul></li>
  <li><a href="#how-to-run-the-same-anova-using-r-instead" id="toc-how-to-run-the-same-anova-using-r-instead" class="nav-link" data-scroll-target="#how-to-run-the-same-anova-using-r-instead">How to run the same ANOVA using R instead</a></li>
  <li><a href="#that-is-the-one-way-anova" id="toc-that-is-the-one-way-anova" class="nav-link" data-scroll-target="#that-is-the-one-way-anova">That is the One-Way Anova</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Chapter 4 ANOVAs Part I</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="anova-part-i" class="level2">
<h2 class="anchored" data-anchor-id="anova-part-i">ANOVA: Part I</h2>
<p>In this chapter we are going to discuss the family of <strong>Analysis of Variance</strong> (ANOVA) analyses that are typical in HHS research. These start from a place of <em>between groups</em> analyses that focus on comparison of means scores across multiple groups. That is the One-Way ANOVA. Other ANOVA models will include:</p>
<ol type="1">
<li>Multiple IVs or factors (factorial ANOVA)</li>
<li>Covariates or control variables (ANCOVA)</li>
<li>Multiple Outcomes (MANOVA)</li>
<li>Repeated-measures ANOVA (RMANOVA)</li>
<li>mixed-design ANOVAs, which include both within-person and between-person factors.</li>
</ol>
</section>
<section id="what-is-an-anova-why-would-you-do-one" class="level2">
<h2 class="anchored" data-anchor-id="what-is-an-anova-why-would-you-do-one">What is an ANOVA? Why would you do one?</h2>
<p>ANOVAs are an analysis that is typically done to compare means across 3 or more groups.</p>
<p>Let’s take for example a comparison of Hmong American adolescents who were classified into three groups based on their experiences as cultural and language brokers.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hmong are a refugee group originally from the mountain regions of Laos who were drawn into the Vietnam conflict by US forces. Upon US withdrawal from SE Asia, many Hmong fled persecution and violence and were placed in refugee camps in Thailand. Many were granted refugee status to come to the US. There are an estimated 400,000 Hmong in the USA with the largest populations in California, Minnesota, Wisconsin, and North Carolina.</p>
<p>Cultural and language brokering refers to children in immigrant families serving as translators/interpreters for non-English speaking parents and also teaching parents about social rules and norms in the US.</p>
<p><span class="citation" data-cites="subramoney2025">(<a href="#ref-subramoney2025" role="doc-biblioref"><strong>subramoney2025?</strong></a>)</span></p>
<p><span class="citation" data-cites="im2025">(<a href="#ref-im2025" role="doc-biblioref"><strong>im2025?</strong></a>)</span></p>
<p><span class="citation" data-cites="vang2019a">(<a href="#ref-vang2019a" role="doc-biblioref"><strong>vang2019a?</strong></a>)</span></p>
</div>
</div>
<p>In a survey of 7th grade adolescents, I asked students about experiences as cultural and language brokers. Based on those responses, I classified students into one of three groups: (1) Low, (2) Moderate, and (3) High. The classification reflected adolescents who reported very low engagement in cultural/language brokering or just doings things like answering the phone. Moderate engagement was some frequency of doing translating, particularly at school. High engagement referred to adolescents who frequently translated for parents including in “high stakes” settings like medical appointments.</p>
<p>My research questions included:</p>
<ul>
<li>Do Hmong adolescents who engage in high levels of cultural and language brokering differ from adolescents who are lower in cultural and language brokering?</li>
<li>In terms of self-esteem, conflict with parents, and GPA</li>
</ul>
<p>One main hypothesis I had was:</p>
<ul>
<li>Hmong adolescents who engage in high levels of cultural and language brokering will report higher mean levels of culture-related conflicts with parents compared to adolescents who engage in moderate and low engagement.</li>
</ul>
<p>From the perspective of an ANOVA, the null hypothesis would be: <span class="math display">\[H_0: \mu_{low} = \mu_{moderate} = \mu_{high}\]</span> Where <span class="math inline">\(\mu\)</span> refers to group means</p>
<p>An appropriate statistical test to evaluate this hypothesis would be an ANOVA because of the comparison of means across three groups. The specific details of ANOVAs, computing <span class="math inline">\(F\)</span> statistics, and other technical points come later. Here we are focused on the conceptual aspect of what ANOVA is testing, how to run the ANOVA, and its interpretation.</p>
<p>The central test statistic in ANOVA is the <span class="math inline">\(F\)</span> statistic. Just like when we do a <span class="math inline">\(t\)</span>-test, there is a critical values associated with <span class="math inline">\(F\)</span> that is determined by the chosen significance level (<span class="math inline">\(\alpha\)</span>, often .05) and the model degrees of freedom (<span class="math inline">\(df\)</span>). Unlike a <span class="math inline">\(t\)</span>-test, however, the <span class="math inline">\(F\)</span>-distribution requires two sets of degrees of freedom: one for the numerator (between-groups variation) and one for the denominator (within-groups variation).</p>
<p>The <span class="math inline">\(F\)</span> statistic is computed from the sample data. If the obtained <span class="math inline">\(F\)</span> statistic exceeds the critical value, or equivalently if the <span class="math inline">\(p\)</span>-value is less than <span class="math inline">\(\alpha\)</span>, the researcher rejects the null hypothesis and concludes that there is a statistically significant difference among the population means. Specifically, the conclusion is that at least one group mean differs from at least one other group mean, although the ANOVA itself does not indicate which groups differ. Follow-up analyses, such as <em>posthoc</em> tests, are needed to determine the specific group differences.</p>
<p>A common follow up test is the <span class="math inline">\(Tukey\)</span> Honestly Difference test that will do group-by-group <strong>posthoc</strong> tests to identify specific statstically significant differences across the three groups (as in our case).</p>
<p>Typically it is also helpful to see the means stratified by group and to compute a measure of effect size, <span class="math inline">\(\eta^2\)</span> or <span class="math inline">\(\omega^2\)</span>.</p>
</section>
<section id="technical-details-about-anovas" class="level2">
<h2 class="anchored" data-anchor-id="technical-details-about-anovas">Technical Details about ANOVAs</h2>
<section id="why-cant-we-just-stick-with-t-tests" class="level3">
<h3 class="anchored">Why can’t we just stick with <span class="math inline">\(t-tests\)</span>?</h3>
<p>For the above study, I might have thought about doing <span class="math inline">\(t-tests\)</span>. For example, couldn’t I have just done one <span class="math inline">\(t-test\)</span> comparing the LOW group to the moderate group, then another <span class="math inline">\(t-test\)</span> comparing the LOW to the HIGH group and another to test moderate versus HIGH?</p>
<p>While that is possible, there is a statistical problem that occurs when running multiple tests. When running multiple tests, researchers run the risk of creating <em>Type I Error Inflation</em>. What that means is that multiple tests increase the risk of committing Type I errors (rejecting a null that really is true, i.e., claiming a significant difference that is not really different).</p>
<p>Think about the various different research questions we might have related to group comparisons: Is motivation to exercise different across adults who played different types of sports? Are reports of anxiety different across different sexual orientation and gender identity groups?</p>
<p>These questions involve tests of more than two groups and doing multiple <span class="math inline">\(t-tests\)</span> would raise lead to <em>alpha inflation</em> and raise the <em>familywise error rate</em>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Family wise Error Rate (FWE)
</div>
</div>
<div class="callout-body-container callout-body">
<p>When we think of Type I errors, we think about a specific test. For example, what is the probability of us making a Type I error when doing a <span class="math inline">\(t_test\)</span> to evaluate if males have higher self-esteem than females. This is a <strong>per-comparison error rate</strong></p>
<p>When we conduct multiple statistical tests, such as a series of pairwise <span class="math inline">\(t_test\)</span>s across several groups or outcomes, those tests form a <em>family of tests</em>. The probability of making at least one Type I error across that entire set of tests is called the <strong>familywise error rate (FWE)</strong>.</p>
<p><em>FWE</em> refers to the probability of incorrectly rejecting at least one true null hypothesis when multiple statistical tests are conducted. In general, as the number of statistical tests increases, the likelihood of obtaining a statistically significant result purely by chance also increases.</p>
<p>Consequently, the FWE becomes larger than the target significance level (e.g., α = .05) used for any individual test.</p>
<p>The formula to compute the increase in the FWE is <span class="math inline">\(\alpha_{FWE} = 1 - (1 - \alpha)^K\)</span></p>
<p>If doing 3 comparisons:</p>
<p><span class="math inline">\(H_0: \mu_1 = \mu_2 = \mu_3\)</span></p>
<p><span class="math inline">\(\alpha_{fw} = 1 - (.95)(.95)(.95) = 1 - .95^3 = 1 - .8574 = .1426\)</span></p>
<p>This suggests that, if all null hypotheses are true and the three tests are independent, there is about a 14.3% chance of obtaining at least one statistically significant result by chance alone.</p>
<p>Put differently, even when there are no real group differences, running three separate tests at (<span class="math inline">\(\alpha\)</span> = .05) makes it more likely that random sampling variation will make one of them appear statistically significant.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that the above procedure assumes <em>independent tests</em>.</p>
<p>A different approach is the <strong>Bonferroni bound</strong>:</p>
<p><span class="math display">\[\alpha_{FW} \leq 3(.05) = .15\]</span></p>
<p>This means that if we conduct three tests, each at (<span class="math inline">\(\alpha\)</span> = .05), the probability of making <strong>at least one</strong> Type I error is no greater than (15%).The <strong>Bonferroni</strong> bound does <strong>not</strong> assume that the tests are independent. It works even when the tests are related or share data, as pairwise comparisons among group means often do.</p>
<p>Because it gives an upper limit rather than an exact probability, it may be somewhat conservative. In this example, the actual family-wise error rate could be below (15%), but Bonferroni guarantees that it will not exceed (15%).</p>
<p>When running multiple tests, The <strong>Bonferroni correction</strong> is a simple way to keep the overall probability of one or more false positives at or below a chosen family-wise significance level.</p>
<p>The rule is:</p>
<p><span class="math inline">\(\alpha\_{\text{per test}} = \frac{\alpha_{\text{family-wise}}}{\text{number of tests}}\)</span></p>
<p>If we want the family-wise error rate to stay at (.05) and we have three comparisons:</p>
<p><span class="math inline">\(\alpha\_{\text{per test}} = \frac{.05}{3} = .0167\)</span></p>
<p>Therefore, instead of using (<span class="math inline">\(p\)</span> &lt; .05) for each comparison, we use:</p>
<p><span class="math inline">\(p &lt; .0167\)</span></p>
<p>A comparison must have a <span class="math inline">\(p\)</span>-value below (.0167) to be statistically significant after the Bonferroni correction.</p>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<p>Imagine the three pairwise tests produce these results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th style="text-align: right;">Original <span class="math inline">\(p\)</span>-value</th>
<th>Significant using <span class="math inline">\(p\)</span> &lt;.05)?</th>
<th>Significant after Bonferroni?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group 1 vs.&nbsp;Group 2</td>
<td style="text-align: right;">.011</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Group 1 vs.&nbsp;Group 3</td>
<td style="text-align: right;">.021</td>
<td>Yes</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Group 2 vs.&nbsp;Group 3</td>
<td style="text-align: right;">.004</td>
<td>Yes</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p>After the <em>Bonferroni</em> correction, the cutoff is (.0167):</p>
<ul>
<li>.011 &lt; .0167), so Group 1 vs.&nbsp;Group 2 is significant.</li>
<li>.021 &gt; .0167), so Group 1 vs.&nbsp;Group 3 is <strong>not</strong> significant.</li>
<li>.004 &lt; .0167), so Group 2 vs.&nbsp;Group 3 is significant.</li>
</ul>
</section>
<section id="another-way-adjust-the-p-values" class="level2">
<h2 class="anchored" data-anchor-id="another-way-adjust-the-p-values">Another way: adjust the <span class="math inline">\(p\)</span>-values</h2>
<p>Instead of lowering the cutoff, we can multiply each <span class="math inline">\(p\)</span>-value by the number of tests:</p>
<p><span class="math display">\[p_{\text{adjusted}} = p \times m\]</span></p>
<p>where <span class="math inline">\(m\)</span> is the number of comparisons.</p>
<p>For three tests:</p>
<p><span class="math display">\[p_{\text{adjusted}} = 3p\]</span></p>
<p>Any adjusted <span class="math inline">\(p\)</span>-value above 1 is reported as 1. `</p>
<p>For the earlier example:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 27%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th style="text-align: right;">Original <span class="math inline">\(p\)</span>-value</th>
<th style="text-align: right;">Bonferroni-adjusted <span class="math inline">\(p\)</span>-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group 1 vs.&nbsp;Group 2</td>
<td style="text-align: right;">.011</td>
<td style="text-align: right;">.033</td>
</tr>
<tr class="even">
<td>Group 1 vs.&nbsp;Group 3</td>
<td style="text-align: right;">.021</td>
<td style="text-align: right;">.063</td>
</tr>
<tr class="odd">
<td>Group 2 vs.&nbsp;Group 3</td>
<td style="text-align: right;">.004</td>
<td style="text-align: right;">.012</td>
</tr>
</tbody>
</table>
<p>We then compare the adjusted values to (.05):</p>
<ul>
<li>(.033 &lt; .05): significant</li>
<li>(.063 &gt; .05): not significant</li>
<li>(.012 &lt; .05): significant</li>
</ul>
<p>This produces the same decisions as using the corrected cutoff of .0167.</p>
</section>
<section id="important-tradeoff" class="level2">
<h2 class="anchored" data-anchor-id="important-tradeoff">Important tradeoff</h2>
<p>The <em>Bonferroni</em> correction reduces false positives, but it also makes it harder to find real effects.</p>
<p>In other words:</p>
<ul>
<li>It lowers the chance of a <strong>Type I error</strong> (false positive).</li>
<li>It can increase the chance of a <strong>Type II error</strong> (missing a real difference).</li>
</ul>
<p>For a small number of planned comparisons, such as three, Bonferroni is easy to use and often reasonable. For many comparisons, it may be too strict, and other methods—such as the Holm correction or <em>Tukey’s HSD</em>—may be better choices.</p>
</section>
</div>
</div>
</section>
<section id="anova-overcomes-the-alpha-inflation-problem-by-focusing-on-one-test." class="level3">
<h3 class="anchored" data-anchor-id="anova-overcomes-the-alpha-inflation-problem-by-focusing-on-one-test.">ANOVA overcomes the alpha inflation problem by focusing on one test.</h3>
<ul>
<li>The <span class="math inline">\(F\)</span> test is an omnibus test of whether there are mean differences across multiple levels of a factor
<ul>
<li>That one test controls FWE rates and reduces risk of Type I error</li>
<li>The test only suggests that mean differences exist in two at least one pair of group means</li>
<li>Often follow-up tests are needed to sort out specific differences across groups or levels of factors</li>
</ul></li>
</ul>
</section>
</section>
<section id="one-way-anova-details" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova-details">One Way ANOVA details</h2>
<p>Addresses mean difference questions across multiple groups.</p>
<ul>
<li>Conceptually ANOVAs are extensions of <span class="math inline">\(t_test\)</span>s
<ul>
<li>Doing an ANOVA with two groups would be the same as a <span class="math inline">\(t_test\)</span></li>
</ul></li>
<li>ANOVAs are multiple group, non-directional tests</li>
<li>Use <strong>one</strong> Type I error rate</li>
</ul>
<p>The <em>technical</em> statistical test asks:</p>
<ul>
<li>Are the observed group differences larger than would be expected due to random variation?</li>
</ul>
<p>Instead of comparing two means directly, ANOVA compares:</p>
<ul>
<li>Between-group variability to within-group variability</li>
</ul>
<p>So while our goal is to compare means, the Analysis of <strong>Variance</strong> includes evaluations of variances as a means to test for group differences.</p>
<hr>
</section>
<section id="the-logic-of-anova" class="level2">
<h2 class="anchored" data-anchor-id="the-logic-of-anova">The Logic of ANOVA</h2>
<p>If groups truly differ:</p>
<ul>
<li>Group means should be far apart and individuals within groups should be relatively similar</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-anova-signal-noise" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anova-signal-noise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter-4-ANOVAs-Part-I_files/figure-html/fig-anova-signal-noise-1.png" class="img-fluid figure-img" width="1056">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anova-signal-noise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: ANOVA compares variability between group means with variability within groups. The group means are identical in both panels; only within-group variability changes.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Take this back to a <span class="math inline">\(t_test\)</span> for a moment. The <span class="math inline">\(t_test\)</span> formula is a ratio of mean differences over variability within groups.</p>
<p><span class="math display">\[t =
\frac{\bar X_1-\bar X_2}
{
\sqrt{
s_p^2
\left(
\frac{1}{n_1}+\frac{1}{n_2}
\right)
}}\]</span></p>
<p>The resulting t-ratio is conceptually a ratio of between group differences (in means; the numerator) to within group variation. What this formula basically is saying is that the difference between two groups (variation <em>between groups</em>) is evaluated by standard errors that capture within group differences (how different participants in each group are; <em>within group differences</em>)</p>
</div>
</div>
<p>ANOVA evaluates:</p>
<p><span class="math display">\[F =
\frac{
\text{Between-Group Variance}
}{
\text{Within-Group Variance}
}\]</span></p>
<hr>
</section>
<section id="understanding-the-f-ratio" class="level2">
<h2 class="anchored" data-anchor-id="understanding-the-f-ratio">Understanding the F Ratio</h2>
<p>Let’s think about what this means: The ANOVA is creating a ratio of <em>between group variance</em> to <em>within group variance</em></p>
<ul>
<li>The <strong>between group variance</strong> is going to capture differences in the means across groups - i.e., how the means vary or differ across/between groups</li>
<li>The <strong>within group variance</strong> is going to capture differences in scores within groups, or how different people in the same group are from each other</li>
<li>A bigger F essentially means that groups differences are relatively large relative to within group differences</li>
</ul>
<section id="computing-the-f-ratio" class="level3">
<h3 class="anchored" data-anchor-id="computing-the-f-ratio">Computing the F Ratio</h3>
<p>To compute the F Ratio, we would need to compute the between group variation and the within group variation, then compute that ratio.The resulting ratio can be thought of <strong><em>an index of separation</em></strong> between the groups.</p>
<p>Technically the F Ratio is computed by dividing the <strong>Mean Sum of Squares</strong> for the between group variation <span class="math inline">\(MS_B\)</span> and the <strong>Mean Sum of Squares</strong> for the within-group variation <span class="math inline">\(MS_W\)</span>.</p>
<p>The hand calculation involves computing each of these two values, then creating the ratio.</p>
<hr>
</section>
<section id="example-culture-based-conflicts-with-parents-by-level-of-language-brokering" class="level3">
<h3 class="anchored" data-anchor-id="example-culture-based-conflicts-with-parents-by-level-of-language-brokering">Example: Culture-based conflicts with parents by level of language brokering</h3>
<p>Remember, I want to compare mean levels of culture-based conflicts in a sample of adolescents across low, moderate, and high levels of language and cultural brokering.</p>
<p>We will use a few cases first to demonstrate how to calculate the <span class="math inline">\(F\)</span> statistic, then use the full data to run an ANOVA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># These are data I collected in 2009 from a sample of Hmong 7th grade students</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># in Burke County, NC</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># These are just a few cases where I categorized the adolescents based on their</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># participation in "cultural/language brokering" for their parents. For this example I </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># just randomly sampled 10 cases in each of the three conditions</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># I created three categories based on adolescents' involvement in language</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># brokering being 'low' (not much involvement), 'moderate' (answering phone,</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># needing to be home to translate) and 'high' (needing to go to medical appointment,</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># translate across many domains)</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># I want to compare adolescent outcomes across brokering types</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Pretty table</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>demo_table <span class="sc">%&gt;%</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>(<span class="at">rowname_col =</span> <span class="st">"Case"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_number</span>(</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> <span class="fu">c</span>(Low, Medium, High),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">decimals =</span> <span class="dv">2</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"AAFCS Scores by Brokering Group"</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">Low =</span> <span class="st">"Low"</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">Medium =</span> <span class="st">"Moderate"</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">High =</span> <span class="st">"High"</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="iijwugufyb" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#iijwugufyb table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#iijwugufyb thead, #iijwugufyb tbody, #iijwugufyb tfoot, #iijwugufyb tr, #iijwugufyb td, #iijwugufyb th {
  border-style: none;
}

#iijwugufyb p {
  margin: 0;
  padding: 0;
}

#iijwugufyb .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#iijwugufyb .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#iijwugufyb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#iijwugufyb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#iijwugufyb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iijwugufyb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iijwugufyb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iijwugufyb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#iijwugufyb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#iijwugufyb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#iijwugufyb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#iijwugufyb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#iijwugufyb .gt_spanner_row {
  border-bottom-style: hidden;
}

#iijwugufyb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#iijwugufyb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#iijwugufyb .gt_from_md > :first-child {
  margin-top: 0;
}

#iijwugufyb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#iijwugufyb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#iijwugufyb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#iijwugufyb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#iijwugufyb .gt_row_group_first td {
  border-top-width: 2px;
}

#iijwugufyb .gt_row_group_first th {
  border-top-width: 2px;
}

#iijwugufyb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iijwugufyb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#iijwugufyb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#iijwugufyb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iijwugufyb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iijwugufyb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#iijwugufyb .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#iijwugufyb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#iijwugufyb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iijwugufyb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iijwugufyb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iijwugufyb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iijwugufyb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iijwugufyb .gt_left {
  text-align: left;
}

#iijwugufyb .gt_center {
  text-align: center;
}

#iijwugufyb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#iijwugufyb .gt_font_normal {
  font-weight: normal;
}

#iijwugufyb .gt_font_bold {
  font-weight: bold;
}

#iijwugufyb .gt_font_italic {
  font-style: italic;
}

#iijwugufyb .gt_super {
  font-size: 65%;
}

#iijwugufyb .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#iijwugufyb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#iijwugufyb .gt_indent_1 {
  text-indent: 5px;
}

#iijwugufyb .gt_indent_2 {
  text-indent: 10px;
}

#iijwugufyb .gt_indent_3 {
  text-indent: 15px;
}

#iijwugufyb .gt_indent_4 {
  text-indent: 20px;
}

#iijwugufyb .gt_indent_5 {
  text-indent: 25px;
}

#iijwugufyb .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#iijwugufyb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="4" class="gt_heading gt_title gt_font_normal gt_bottom_border">AAFCS Scores by Brokering Group</td>
</tr>
<tr class="gt_col_headings even">
<th id="a::stub" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"></th>
<th id="Low" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Low</th>
<th id="Medium" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Moderate</th>
<th id="High" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">High</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<th id="stub_1_1" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">1</th>
<td class="gt_row gt_right" headers="stub_1_1 Low">31.00</td>
<td class="gt_row gt_right" headers="stub_1_1 Medium">30.00</td>
<td class="gt_row gt_right" headers="stub_1_1 High">25.00</td>
</tr>
<tr class="even">
<th id="stub_1_2" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">2</th>
<td class="gt_row gt_right" headers="stub_1_2 Low">19.00</td>
<td class="gt_row gt_right" headers="stub_1_2 Medium">22.00</td>
<td class="gt_row gt_right" headers="stub_1_2 High">29.00</td>
</tr>
<tr class="odd">
<th id="stub_1_3" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">3</th>
<td class="gt_row gt_right" headers="stub_1_3 Low">26.00</td>
<td class="gt_row gt_right" headers="stub_1_3 Medium">36.00</td>
<td class="gt_row gt_right" headers="stub_1_3 High">35.00</td>
</tr>
<tr class="even">
<th id="stub_1_4" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">4</th>
<td class="gt_row gt_right" headers="stub_1_4 Low">42.00</td>
<td class="gt_row gt_right" headers="stub_1_4 Medium">21.00</td>
<td class="gt_row gt_right" headers="stub_1_4 High">34.00</td>
</tr>
<tr class="odd">
<th id="stub_1_5" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">5</th>
<td class="gt_row gt_right" headers="stub_1_5 Low">35.00</td>
<td class="gt_row gt_right" headers="stub_1_5 Medium">15.00</td>
<td class="gt_row gt_right" headers="stub_1_5 High">31.00</td>
</tr>
<tr class="even">
<th id="stub_1_6" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">6</th>
<td class="gt_row gt_right" headers="stub_1_6 Low">27.00</td>
<td class="gt_row gt_right" headers="stub_1_6 Medium">40.00</td>
<td class="gt_row gt_right" headers="stub_1_6 High">32.00</td>
</tr>
<tr class="odd">
<th id="stub_1_7" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">7</th>
<td class="gt_row gt_right" headers="stub_1_7 Low">23.00</td>
<td class="gt_row gt_right" headers="stub_1_7 Medium">33.00</td>
<td class="gt_row gt_right" headers="stub_1_7 High">30.00</td>
</tr>
<tr class="even">
<th id="stub_1_8" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">8</th>
<td class="gt_row gt_right" headers="stub_1_8 Low">15.00</td>
<td class="gt_row gt_right" headers="stub_1_8 Medium">30.00</td>
<td class="gt_row gt_right" headers="stub_1_8 High">33.00</td>
</tr>
<tr class="odd">
<th id="stub_1_9" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">9</th>
<td class="gt_row gt_right" headers="stub_1_9 Low">19.00</td>
<td class="gt_row gt_right" headers="stub_1_9 Medium">38.00</td>
<td class="gt_row gt_right" headers="stub_1_9 High">37.00</td>
</tr>
<tr class="even">
<th id="stub_1_10" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">10</th>
<td class="gt_row gt_right" headers="stub_1_10 Low">27.00</td>
<td class="gt_row gt_right" headers="stub_1_10 Medium">31.00</td>
<td class="gt_row gt_right" headers="stub_1_10 High">39.00</td>
</tr>
<tr class="odd">
<th id="stub_1_11" class="gt_row gt_left gt_stub" data-quarto-table-cell-role="th" scope="row">Mean</th>
<td class="gt_row gt_right" headers="stub_1_11 Low">26.40</td>
<td class="gt_row gt_right" headers="stub_1_11 Medium">29.60</td>
<td class="gt_row gt_right" headers="stub_1_11 High">32.50</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Note: This table shows values of AAFCS scores (Asian American Family Conflicts Scale) for 10 randonly select 7th graders from each of the three cultural/language brokering groups. The bottom row shows the group means.</p>
<p>The first step in <em>manually</em> computing an ANOVA F Statistic is to compute the Mean Squares of the Between group variance</p>
<p>Quick reminder the variance of a set of scores is computed by summing deviations from a mean</p>
<p><span class="math display">\[s^2 = \frac{\sum (X_i - \bar{X})^2}{n - 1}\]</span> The <em>variance</em> for group American-Oriented Group would be the sum of squared deviations, divided by the sample size (minus 1). We would take each score, subtract the group mean, square that value, then sum that number, then divide by 9.</p>
<p>The analogous formula for the <em>Between-Group Variance</em> (<span class="math inline">\(MS_B\)</span>) = <span class="math inline">\(SS_B/df\)</span></p>
<p><span class="math inline">\(SS_B/df\)</span> is computed as an extension of the variance for a sample (above). The differences between each group mean <em>j</em> and the <em>grand mean</em> squared are multiplied by the group sizes <span class="math inline">\(N_j\)</span> and then summed to get the <span class="math inline">\(SS_B\)</span>. The degrees of freedom are the number of groups <span class="math inline">\(K - 1\)</span>.</p>
<p><span class="math display">\[= \sum_{j=1}^{K} N_j (\bar{X}_j - \bar{X})^2\]</span></p>
<p><span class="math display">\[df = K-1\]</span></p>
<p>Which leads to:</p>
<p><span class="math display">\[MS_B = \frac{SS_B}{df}\]</span></p>
<p>In addition to computing the <span class="math inline">\(MS_B\)</span> we also compute the <span class="math inline">\(SS_W\)</span></p>
<p>That means that the <span class="math inline">\(F\)</span> statistic is comparing/computing two sources of variance: Between group variance and within group variance.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <em>Between Groups</em> SS is just the deviations of each group mean <strong>from the grand</strong> mean squared, then summed, and multiplied by the number of values in each group. That value is then divided by the between groups <span class="math inline">\(df\)</span> which is <span class="math inline">\(K\)</span>-1 (or # of groups, minus 1).</p>
<p>In our case since these groups are equal, then <span class="math inline">\(N_1\)</span> = <span class="math inline">\(N_2\)</span> = <span class="math inline">\(N_3\)</span> = 10</p>
<p>The mean of the groups are:</p>
<p><span class="math inline">\(\bar{Low}\)</span> = 26.40 <span class="math inline">\(\bar{moderate}\)</span> = 29.60 <span class="math inline">\(\bar{High}\)</span> = 32.50 and the <strong>grand mean</strong> = (26.40+29.60+32.50)/3 = 29.50</p>
</div>
</div>
<p>The computation for <span class="math inline">\(SS_B\)</span> then would be</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mean_low<span class="ot">&lt;-</span><span class="fl">26.40</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mean_med<span class="ot">&lt;-</span><span class="fl">29.60</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>mean_hi <span class="ot">&lt;-</span><span class="fl">32.50</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>grand_mean<span class="ot">&lt;-</span><span class="fl">29.50</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>group_size_low<span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>group_size_med<span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>group_size_hi <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>SS_B <span class="ot">&lt;-</span> ((mean_low<span class="sc">-</span>grand_mean)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span><span class="dv">10</span> <span class="sc">+</span> ((mean_med<span class="sc">-</span>grand_mean)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span><span class="dv">10</span> <span class="sc">+</span> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  ((mean_hi<span class="sc">-</span>grand_mean)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span><span class="dv">10</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Then the MS_B is calculated as SS_B/K-1 or</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>MS_B <span class="ot">&lt;-</span> SS_B<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>MS_B</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 93.1</code></pre>
</div>
</div>
<p>The computation of the <span class="math inline">\(SS_W\)</span> is a bit more complicated in that this captures within group variance and necessitates subtracting each individual score from the <em>group</em> mean.</p>
<p>The group means are 26.40, 29.60, and 32.50 for the Low, Moderate, and High brokering groups, respectively. Individual participant’s scores within each group are deviated from those means, then squared, then summed. Those values capture within group variance.</p>
<p><span class="math display">\[ SS_W = \sum_{j=1}^{K}\sum_{i=1}^{n_j}(X_{ij}-\bar{X}_{j})^2 \]</span></p>
<p><span class="math display">\[X_ij\]</span> = The i or individual score in group j (low, moderate, high)</p>
<p><span class="math display">\[\bar{X}_j\]</span> = The group mean, e.g., the low group mean of 26.40</p>
<p>So each deviation in a group squared, then summed together, then summed across the groups</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create group means in the data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate command sorts, sort scores in aafcs by brok_three, using toy_brokering</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># note "toy" is just a term for a practice dataset</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># aggregate using means</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>group_means <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(aafcs <span class="sc">~</span> brok_three, <span class="at">data =</span> toy_brokering, mean)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the means back into the data using "merge"</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># merge the group_means back in as a variable, sort by the brok_three</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># so each participant in a group gets the group mean as their score</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># suffixes just gives the name to the variable</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>toy_brokering <span class="ot">&lt;-</span> <span class="fu">merge</span>(toy_brokering, group_means, <span class="at">by =</span> <span class="st">"brok_three"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">suffixes =</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"_mean"</span>))</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Squared deviations from group mean</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an object call deviations</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># that is going to be scores for each participants' aafcs score</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># subtracting out their group mean scores - deviated from a group mean</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># then those values are squared to get the squared deviations</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>toy_brokering<span class="sc">$</span>deviations<span class="ot">&lt;-</span> (toy_brokering<span class="sc">$</span>aafcs <span class="sc">-</span> toy_brokering<span class="sc">$</span>aafcs_mean)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Sum them up to get the total SS_W</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>SS_W <span class="ot">&lt;-</span> <span class="fu">sum</span>(toy_brokering<span class="sc">$</span>deviations)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Just print the SS_W value</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>SS_W</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1317.3</code></pre>
</div>
</div>
<p>Then the within-groups mean square is computed as:</p>
<p><span class="math display">\[MS_W = \frac{SS_W}{df_W}\]</span></p>
<p>where</p>
<p><span class="math display">\[df_W = N - K\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">=</span> <span class="dv">3</span> <span class="co"># Number of groups</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df_b <span class="ot">=</span> k<span class="dv">-1</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">30</span> <span class="co"># sample size</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>df_w <span class="ot">=</span> n<span class="sc">-</span>k</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>MS_W <span class="ot">=</span> SS_W<span class="sc">/</span>df_w</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>MS_W</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48.78889</code></pre>
</div>
</div>
<p>The F statistic is then computed as:</p>
<p><span class="math display">\[F = \frac{MS_B}{MS_W}\]</span></p>
<p>Large values of F indicate that between-group variability is much larger than within-group variability, suggesting that at least one group mean differs from the others.</p>
<p>The null hypothesis is <span class="math display">\[H_0 = \mu_1 = \mu_2 = \mu_3\]</span></p>
<p>where <span class="math inline">\(mu\)</span> is each group mean.</p>
<p>The <span class="math inline">\(F\)</span> is evaluated for statistical significance if the test statistic we just computed is <em>more extreme</em> than the critical value for <span class="math inline">\(F\)</span> at our chosen p value and the model number of degrees of freedom.</p>
<p>At <span class="math inline">\(a\)</span> &lt; .05 with degrees of freedom of 2 and 27</p>
<ul>
<li>These are the <span class="math inline">\(df\)</span> for the <span class="math inline">\(MS_B\)</span> which is <span class="math inline">\(K-1\)</span> and <span class="math inline">\(MS_W\)</span> which is <span class="math inline">\(N-K\)</span></li>
</ul>
<p>we can consult a table to see that the critical value is 3.35 for this p value and combination of <span class="math inline">\(df\)</span></p>
<p>Alternatively we can use an R function to compute the critical value</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Critical F for alpha = .05</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(.<span class="dv">95</span>, <span class="at">df1 =</span> <span class="dv">2</span>, <span class="at">df2 =</span> <span class="dv">27</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.354131</code></pre>
</div>
</div>
<p>Our value of</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>F_Stat <span class="ot">=</span> MS_B<span class="sc">/</span>MS_W</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>F_Stat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.908221</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>F_Stat <span class="sc">&gt;</span> <span class="fl">3.35</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
</section>
</section>
<section id="how-to-run-the-same-anova-using-r-instead" class="level2">
<h2 class="anchored" data-anchor-id="how-to-run-the-same-anova-using-r-instead">How to run the same ANOVA using R instead</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># aov command</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># broker_anova = an object that includes the results</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># affcs ~ brok_three = aafcs scores conditioned on brok_three</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># data is the dataset to use</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># summary is the command/function to read out the results</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>broker_anova<span class="ot">&lt;-</span><span class="fu">aov</span>(aafcs <span class="sc">~</span> brok_three, <span class="at">data =</span> toy_brokering)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(broker_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
brok_three   2  186.2   93.10   1.908  0.168
Residuals   27 1317.3   48.79               </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we will run an ANOVA with the actual data n = 85</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that missing data takes this down to n = 80</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>broker_n85 <span class="ot">&lt;-</span> <span class="fu">aov</span>(aafcs <span class="sc">~</span> brok_three,<span class="at">data=</span>brokering_df)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(broker_n85)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
brok_three   2    455   227.5   3.511 0.0347 *
Residuals   77   4990    64.8                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
13 observations deleted due to missingness</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Since this produced a statistically significant F, we will typically want to do</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># follow up tests and to see the means as well</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Means by group in the full data</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">model.tables</span>(broker_n85, <span class="at">type =</span> <span class="st">"means"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tables of means
Grand mean
     
26.8 

 brok_three 
      Low Medium  High
    24.27  29.57 28.41
rep 37.00  21.00 22.00</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Then the posthoc test</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(broker_n85)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = aafcs ~ brok_three, data = brokering_df)

$brok_three
                 diff         lwr       upr     p adj
Medium-Low   5.301158  0.04497224 10.557344 0.0476073
High-Low     4.138821 -1.04059837  9.318240 0.1428085
High-Medium -1.162338 -7.03155893  4.706884 0.8840506</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size for the overall effect</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>eta_sq<span class="ot">=</span> <span class="dv">455</span> <span class="sc">/</span> (<span class="dv">455</span><span class="sc">+</span> <span class="dv">4990</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>eta_sq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0835629</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Sample Write up
</div>
</div>
<div class="callout-body-container callout-body">
<p>A one-way analysis of variance (ANOVA) was conducted to examine differences in AAFCS scores across participants with low, moderate, and high levels of cultural brokering. There was a statistically significant F(2, 77) = 3.51, p = .035, η² = .084 indicating mean differences in AAFCS scores across groups. Group means indicated that participants in the moderate brokering group (M = 29.57) reported the highest AAFCS scores, followed by the high brokering group (M = 28.41) and the low brokering group (M = 24.27).</p>
<p><strong>Posthoc</strong> tests (Tukey’s HSD) suggested that the moderate brokering group scored significantly higher than the low brokering group (mean difference = 5.30, 95% CI [0.04, 10.56], p = .048). The differences between the high and low brokering groups (mean difference = 4.14, p = .143) and between the high and moderate brokering groups (mean difference = -1.16, p = .884) were not statistically significant.</p>
</div>
</div>
<table class="caption-top table">
<caption>One-Way ANOVA for AAFCS by Brokering Group</caption>
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: right;">SS</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">MS</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">η²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Between Groups</td>
<td style="text-align: right;">455.04</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">227.52</td>
<td style="text-align: right;">3.51</td>
<td style="text-align: right;">.035</td>
<td style="text-align: right;">.084</td>
</tr>
<tr class="even">
<td>Within Groups</td>
<td style="text-align: right;">4989.76</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">64.80</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">5444.80</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</section>
<section id="that-is-the-one-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="that-is-the-one-way-anova">That is the One-Way Anova</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter 3 Data Management and R.html" class="pagination-link" aria-label="Chapter 3: Data Cleaning and Getting into R">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Chapter 3: Data Cleaning and Getting into R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>